services:
    blaatpraat.username.controller:
        class: blaatpraat\username\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'

    blaatpraat.username.listener:
        class: blaatpraat\username\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }
